# Generated by Django 5.0.2 on 2024-03-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interpreter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpreter',
            old_name='num_successful_requests',
            new_name='total_successful_requests',
        ),
    ]
